# Generated by Django 4.1.7 on 2023-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(default='', max_length=40)),
                ('Product', models.CharField(max_length=30)),
                ('Review', models.TextField(max_length=330)),
                ('Stars', models.IntegerField(default=1)),
            ],
        ),
    ]
