# Generated by Django 4.1.7 on 2023-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='Review_title',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='Product',
            field=models.CharField(default='', max_length=30),
        ),
    ]
