# Generated by Django 4.1.7 on 2023-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series', models.CharField(max_length=30)),
                ('Color', models.CharField(max_length=15)),
                ('Processor', models.CharField(max_length=30)),
                ('Memory', models.IntegerField()),
                ('Ram', models.IntegerField()),
                ('Screen', models.CharField(max_length=120)),
                ('Camera', models.CharField(max_length=40)),
                ('Battery', models.CharField(max_length=15)),
            ],
        ),
    ]
