# Generated by Django 4.1.7 on 2023-04-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_smartphones_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='In_stock',
            field=models.BooleanField(default=True),
        ),
    ]
