# Generated by Django 4.1.7 on 2023-04-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_smartphones_in_stock_smartphones_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='Connectivity',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='FiveG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='GPU',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='Interfaces',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='MicroSD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='Networks',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='OS',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='Options',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='Sizes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='TwoSIM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='Warranty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='Weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='Wireless_charging',
            field=models.BooleanField(default=False),
        ),
    ]
